version: '2'
networks:
  elk:
services:
  elasticsearch:
    image: elasticsearch:7.14.1
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk
  kibana:
    image: kibana:7.14.1
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    networks:
      - elk
